version: '3.8'

services:
  audio-transcription-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - WHISPER_MODEL=base
      - MAX_FILE_SIZE_MB=100
      - CORS_ORIGINS=*
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/tmp/audio-transcription
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s